version: 2
registries:
  npm-pkg-checkmarx:
    type: npm-registry
    url: https://npm.pkg.github.com/checkmarxdev
    token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-pkg-checkmarx
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"  
