feature: ['feature/*', 'feat/*']

bug: ['bug/*', 'fix/*', 'hotfix/*']

chore: ['chore/*', 'refactor/*', 'cleanup/*']

documentation: ['docs/*', 'doc/*']

ci/cd: ['ci/*', 'cd/*', 'pipeline/*']

dependencies: ['deps/*', 'dep/*']

security: ['security/*', 'sec/*']

AST: ['AST-*']
