feature:
  - head-branch: ['^feature/', '^feat/']

bug:
  - head-branch: ['^bug/', '^fix/', '^hotfix/']

chore:
  - head-branch: ['^chore/', '^refactor/', '^cleanup/']

documentation:
  - head-branch: ['^docs/', '^doc

ci/cd:
  - head-branch: ['^ci/', '^cd/', '^pipeline/']

dependencies:
  - head-branch: ['^deps/', '^dep

security:
  - head-branch: ['^security/', '^sec/']

AST:
  - head-branch: '^AST-'