name: AST Azure wrapper CI

on: [pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 10
        uses: actions/setup-node@v2.4.1
        env:
          INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 10
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: npm install
        run: |
          npm cache verify
          npm install
          cd cxAstScan/
          npm install --ignore-engines
      - run: npm run build
      - name: Run tests
        env:
          CX_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CX_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CX_BASE_URI: ${{ secrets.BASE_URI }}
          CX_TENANT: ${{ secrets.TENANT }}
        run: npm test

  cx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          project_name: ast-cli-azure-plugin
          branch: master
          base_uri: ${{ secrets.BASE_URI }}
          cx_tenant: ${{ secrets.TENANT }}
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
          additional_params: --tags galactica-team
