name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cxAstScan

    strategy:
      matrix:
        #node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [ 10.24.1 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env:
          INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 12
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: npm install
        run: npm install
      - run: npm run build
      - name: Run tests
        env:
          CX_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CX_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CX_BASE_URI: ${{ secrets.BASE_URI }}
        run: npm test
