name: Manual Tag Creation

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  tag-creation:
    name: Create and Push Tag
    permissions:
      contents: write  # Required to push git tags
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Tag
        env:
          TAG: ${{ github.event.inputs.tag }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$TAG"
          echo "NEXT_VERSION=$TAG" >> $GITHUB_ENV
          message="$TAG: PR #$PR_NUMBER $PR_TITLE"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "$TAG" -m "$message"
          git push origin "$TAG"
