name: Draft Release

on:
  push:
    branches: [ feature/azo-extension-pipeline ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .


    steps:
      - uses: actions/checkout@v2
      - name: Create VSS Extension
        run: tfx extension create --manifest-globs vss-extension.json
      - name: Create Release
        id: draft_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.vsix"
          asset_name: Checkmarx AST ADO Extension
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"