name: Draft Release

on:
  push:
    branches: [ master ]

env:
  PUBLISHER: CheckmarxASTBeta
  EXTENSION_ID: CheckmarxAST
  EXTENSION_NAME: 'Checkmarx AST Test'
  RELEASE_VERSION: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v2

      - name: Tfx Install
        run: sudo npm install -g tfx-cli

      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Build step
        run: |
          npm install
          cd cxAstScan/
          npm install
      - run: npm run build

      - name: Set version
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.json"]'
        env:
          VERSION: ${{ env.RELEASE_VERSION }}

      - name: Create VSS Extension
        run: npx tfx extension create --manifest-globs vss-extension.json

      - uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name:  Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: true
          release_name: dev
          tag_name: dev
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.PUBLISHER }}.${{ env.EXTENSION_ID }}-${{ env.RELEASE_VERSION }}.vsix
          asset_name: ${{ env.PUBLISHER }}.${{ env.EXTENSION_ID }}-${{ env.RELEASE_VERSION }}.vsix
          asset_content_type: application/zip
