name: Azure AST plugin release

on:
  push:
    tags:
      - "*"

env:
  PUBLISHER: Checkmarx
  EXTENSION_ID: checkmarx-ast-azure-plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: sudo npm install -g tfx-cli

      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Build step
        run: |
          npm install
          cd cxAstScan/
          npm install
      - run: npm run build

      - name: Set new version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set major, minor, patch values
        run: |
          echo "MAJOR_VERSION=$(echo ${{ env.RELEASE_VERSION }} | cut -d. -f1)" >> $GITHUB_ENV
          echo "MINOR_VERSION=$(echo ${{ env.RELEASE_VERSION }} | cut -d. -f2)" >> $GITHUB_ENV
          echo "PATCH_VERSION=$(echo ${{ env.RELEASE_VERSION }} | cut -d. -f3)" >> $GITHUB_ENV

      - name: New version
        run: |
          echo "The new version is ${{ env.RELEASE_VERSION }}"
          echo "The new major version is ${{ env.MAJOR_VERSION }}"
          echo "The new minor version is ${{ env.MINOR_VERSION }}"
          echo "The new patch version is ${{ env.PATCH_VERSION }}"

      - name: Set versions in files
        run: |
          cat <<< $(jq ".version = \"${{ env.RELEASE_VERSION }}\"" ./vss-extension.json) > ./vss-extension.json
          cat <<< $(jq ".version = \"${{ env.RELEASE_VERSION }}\"" ./package.json) > ./package.json
          cat <<< $(jq ".version.Major = ${{ env.MAJOR_VERSION }}" ./cxAstScan/task.json) > ./cxAstScan/task.json
          cat <<< $(jq ".version.Minor = ${{ env.MINOR_VERSION }}" ./cxAstScan/task.json) > ./cxAstScan/task.json
          cat <<< $(jq ".version.Patch = ${{ env.PATCH_VERSION }}" ./cxAstScan/task.json) > ./cxAstScan/task.json

      - name: Create extension
        run: tfx extension create --manifest-globs vss-extension.json

      # Create the release
      - name: Create Release
        uses: softprops/action-gh-release@master
        with:
          release_name: Checkmarx Azure ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
          files: ./${{ env.PUBLISHER }}.${{ env.EXTENSION_ID }}-${{ env.RELEASE_VERSION }}.vsix
          generate_release_notes: true

      - name: Release to marketplance
        run: tfx extension publish --vsix *.vsix --token ${{ secrets.AZURETOKEN }}

      - name: Get latest relase notes
        run: |
          body_release="$(gh api -H "Accept: application/vnd.github.v3+json" /repos/ast-azure-plugin/releases/releases/latest | jq -r '.body' )"
          echo 'BODY_RELEASE='$body_release >> $GITHUB_ENV

      - name: Teams notification
          uses: toko-bifrost/ms-teams-deploy-card@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
            custom-facts: |
              - name: Release :
                value: "${{BODY_RELEASE}}"
            custom-actions: |
              - name: Details
                value: https://github.com/Checkmarx/ast-azure-plugin/releases/tag/${{ env.RELEASE_VERSION }}
