name: Update AST CLI JavaScript Runtime Wrapper Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Specify a version (e.g., 1.2.3). Leave empty for the latest official version."
        required: false
        default: ""

jobs:
  update-js-wrapper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine Version
        id: get_version
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=$(curl -s "https://api.github.com/repos/CheckmarxDev/ast-cli-javascript-wrapper-runtime-cli/releases" | jq -r '[.[] | .tag_name | select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))] | sort_by(split(".") | map(tonumber)) | .[-1]')
          fi

          if [[ -z "$VERSION" || "$VERSION" == "null" ]]; then
            echo "Failed to determine a valid version."
            exit 1
          fi

          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update package.json
        run: |
          sed -i "s|\"@checkmarxdev/ast-cli-javascript-wrapper-runtime-cli\": \"v[0-9]*\\.[0-9]*\\.[0-9]*\"|\"@checkmarxdev/ast-cli-javascript-wrapper-runtime-cli\": \"${VERSION}\"|" cxAstScan/package.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: sudo npm install -g tfx-cli

      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Install Dependencies and Update package-lock.json
        run: |
          cd cxAstScan
          npm install

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add cxAstScan/package.json cxAstScan/package-lock.json
          git commit -m "Update AST CLI JavaScript Wrapper to version ${VERSION}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: Update AST CLI JavaScript Runtime Wrapper to version ${{ env.VERSION }}
          title: Update AST CLI JavaScript Runtime Wrapper to version ${{ env.VERSION }}
          body: |
            Updates the AST CLI JavaScript Runtime Wrapper to version `${{ env.VERSION }}`

            Auto-generated by [create-pull-request][2]
          labels: cxone
          branch: other/update_js_wrapper_${{ env.VERSION }}
